name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "yegekucuk2" --password-stdin
    
    - name: Build the Docker image
      run: docker build . --file /web/Dockerfile --tag yegekucuk2/classifier:${{ github.run_number }}
    
    - name: Tag the Docker image as latest
      run: docker tag yegekucuk2/classifier:${{ github.run_number }} yegekucuk2/classifier:latest
    
    - name: Push the Docker image with run_number tag
      run: docker push yegekucuk2/classifier:${{ github.run_number }}
    
    - name: Push the Docker image with latest tag
      run: docker push yegekucuk2/classifier:latest
